/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartvehiclerentalsystem.frame;

import javax.swing.JOptionPane;
import smartvehiclerentalsystem.InvalidRentalDaysException;
import smartvehiclerentalsystem.car.Car;
import smartvehiclerentalsystem.motobike.Motobike;
import smartvehiclerentalsystem.truck.Truck;

/**
 *
 * @author POL-1-G1B-74
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        rentAMotorbike = new javax.swing.JButton();
        rentAtruck = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        records = new javax.swing.JButton();
        rentACar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        menu.setBackground(new java.awt.Color(153, 0, 51));
        menu.setFont(new java.awt.Font("Snap ITC", 3, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("Menu");

        Heading.setBackground(new java.awt.Color(204, 0, 51));
        Heading.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartvehiclerentalsystem/frame/icon2.png"))); // NOI18N
        Heading.setText("Smart Vehicle Rental System ");

        rentAMotorbike.setBackground(new java.awt.Color(100, 0, 0));
        rentAMotorbike.setFont(new java.awt.Font("Snap ITC", 2, 10)); // NOI18N
        rentAMotorbike.setForeground(new java.awt.Color(255, 0, 0));
        rentAMotorbike.setText("Rent A Motobike");
        rentAMotorbike.setBorderPainted(false);
        rentAMotorbike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentAMotorbikeActionPerformed(evt);
            }
        });

        rentAtruck.setBackground(new java.awt.Color(100, 0, 0));
        rentAtruck.setFont(new java.awt.Font("Snap ITC", 0, 11)); // NOI18N
        rentAtruck.setForeground(new java.awt.Color(255, 0, 0));
        rentAtruck.setText("Rent A Truck");
        rentAtruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentAtruckActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(100, 0, 0));
        Exit.setFont(new java.awt.Font("Snap ITC", 0, 10)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 0, 0));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        records.setBackground(new java.awt.Color(100, 0, 0));
        records.setFont(new java.awt.Font("Snap ITC", 0, 10)); // NOI18N
        records.setForeground(new java.awt.Color(255, 0, 0));
        records.setText("View Rental Records");
        records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordsActionPerformed(evt);
            }
        });

        rentACar.setBackground(new java.awt.Color(100, 0, 0));
        rentACar.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        rentACar.setForeground(new java.awt.Color(255, 0, 0));
        rentACar.setText("Rent A Car");
        rentACar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentACarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(Heading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(rentACar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(rentAMotorbike)))
                .addGap(276, 276, 276)
                .addComponent(rentAtruck)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(252, 252, 252)
                .addComponent(records)
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentAMotorbike)
                    .addComponent(rentAtruck)
                    .addComponent(rentACar))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(records)
                        .addGap(155, 155, 155))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Exit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void rentACarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentACarActionPerformed
        String customerName;

        do {
            customerName = JOptionPane.showInputDialog(this, "Customer Name: ");
            if (customerName == null) {
                return;
            }
            if (customerName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer name cannot be empty. Please try again.");
            }
        } while (customerName.trim().isEmpty());

        String registrationNumber;

        do {
            registrationNumber = JOptionPane.showInputDialog(this, "Registration Number: ");
            if (registrationNumber == null) {
                return;
            }
            if (registrationNumber.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Registration number cannot be empty. Please try again.");
            }
        } while (registrationNumber.trim().isEmpty());

        String brand;
        do {
            brand = JOptionPane.showInputDialog(this, "Brand: ");
            if (brand == null) {
                return;
            }
            if (brand.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Brand cannot be empty. Please try again.");
            }
        } while (brand.trim().isEmpty());

        String model;
        do {
            model = JOptionPane.showInputDialog(this, "Model: ");
            if (model == null) {
                return;
            }
            if (model.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Model cannot be empty. Please try again.");
            }
        } while (model.trim().isEmpty());
        String dailyRateInput;
        do {
            dailyRateInput = JOptionPane.showInputDialog(this, "Daily Rate: ");
            if (dailyRateInput == null) {
                return;
            }
            if (dailyRateInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Daily Rate cannot be empty. Please try again.");
            }
        } while (dailyRateInput.trim().isEmpty());
        String insuranceFeeInput;
        do {
            insuranceFeeInput = JOptionPane.showInputDialog(this, "Insurance Fee:");
            if (insuranceFeeInput == null) {
                return;
            }
            if (insuranceFeeInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Insurance fee cannot be empty. Please try again.");
            }
        } while (insuranceFeeInput.trim().isEmpty());
        String daysInput;
        do {
            daysInput = JOptionPane.showInputDialog(this, "Days: ");
            if (daysInput == null) {
                return;
            }
            if (daysInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Days cannot be empty. Please try again.");
            }
        } while (daysInput.trim().isEmpty());
        try {
            double dailyRate = Double.parseDouble(dailyRateInput.trim());
            double insuranceFee = Double.parseDouble(insuranceFeeInput.trim());
            int days = Integer.parseInt(daysInput.trim());
            if (days <= 0) {
                throw new InvalidRentalDaysException("Rental days must be greater than 0.");
            }

            Car car = new Car(insuranceFee, registrationNumber, brand, model, dailyRate);
            double cost = car.calculateRentalCost(days);

            java.io.FileWriter fw = new java.io.FileWriter("rentals.txt", true);
            fw.write("Customer: " + customerName + " | Type: Car | Reg: " + registrationNumber + " | Days: " + days + " | Total Cost: R" + cost + "\n");
            fw.close();

            JOptionPane.showMessageDialog(this, "Car rented successfully!\nTotal Cost: R" + cost);

        } catch (InvalidRentalDaysException e) {
            JOptionPane.showMessageDialog(this, "Invalid days: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input! Numbers only for rate, fee and days.");
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "File error: " + e.getMessage());
        }
    }//GEN-LAST:event_rentACarActionPerformed

    private void rentAMotorbikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentAMotorbikeActionPerformed
        String customerName;
        do {
            customerName = JOptionPane.showInputDialog(this, "Customer Name: ");
            if (customerName == null) {
                return;
            }
            if (customerName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer name cannot be empty. Please try again.");
            }
        } while (customerName.trim().isEmpty());

        String registrationNumber;

        do {
            registrationNumber = JOptionPane.showInputDialog(this, "Registration Number: ");
            if (registrationNumber == null) {
                return;
            }
            if (registrationNumber.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Registration number cannot be empty. Please try again.");
            }
        } while (registrationNumber.trim().isEmpty());

        String brand;
        do {
            brand = JOptionPane.showInputDialog(this, "Brand: ");
            if (brand == null) {
                return;
            }
            if (brand.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Brand cannot be empty. Please try again.");
            }
        } while (brand.trim().isEmpty());

        String model;
        do {
            model = JOptionPane.showInputDialog(this, "Model: ");
            if (model == null) {
                return;
            }
            if (model.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Model cannot be empty. Please try again.");
            }
        } while (model.trim().isEmpty());

        String dailyRateInput;
        do {
            dailyRateInput = JOptionPane.showInputDialog(this, "Daily Rate: ");
            if (dailyRateInput == null) {
                return;
            }
            if (dailyRateInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Daily Rate cannot be empty. Please try again.");
            }
        } while (dailyRateInput.trim().isEmpty());

        String daysInput;
        do {
            daysInput = JOptionPane.showInputDialog(this, "Number of Days: ");
            if (daysInput == null) {
                return;
            }
            if (daysInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Days cannot be empty. Please try again.");
            }
        } while (daysInput.trim().isEmpty());

        String helmetRentalFee;
        do {
            helmetRentalFee = JOptionPane.showInputDialog(this, "Helmet Rental Fee: ");
            if (helmetRentalFee == null) {
                return;
            }
            if (helmetRentalFee.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Helmet Rental Fee cannot be empty. Please try again.");
            }
        } while (helmetRentalFee.trim().isEmpty());

        try {
            double dailyRate = Double.parseDouble(dailyRateInput.trim());
            double helmetRental = Double.parseDouble(helmetRentalFee.trim());
            int days = Integer.parseInt(daysInput.trim());
            if (days <= 0) {
                throw new InvalidRentalDaysException("Rental days must be greater than 0.");
            }

            Motobike motor = new Motobike(helmetRental, registrationNumber, brand, model, dailyRate);
            double cost = motor.calculateRentalCost(days);

            java.io.FileWriter fw = new java.io.FileWriter("rentals.txt", true);
            fw.write("Customer: " + customerName + " | Type: Car | Reg: " + registrationNumber + " | Days: " + days + " | Total Cost: R" + cost + "\n");
            fw.close();

            JOptionPane.showMessageDialog(this, "Motor Bike rented successfully!\nTotal Cost: R" + cost);

        } catch (InvalidRentalDaysException e) {
            JOptionPane.showMessageDialog(this, "Invalid days: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input! Numbers only for rate, fee and days.");
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "File error: " + e.getMessage());
        }

    }//GEN-LAST:event_rentAMotorbikeActionPerformed

    private void rentAtruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentAtruckActionPerformed
        String customerName;

        do {
            customerName = JOptionPane.showInputDialog(this, "Customer Name: ");
            if (customerName == null) {
                return;
            }
            if (customerName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer name cannot be empty. Please try again.");
            }
        } while (customerName.trim().isEmpty());

        String registrationNumber;

        do {
            registrationNumber = JOptionPane.showInputDialog(this, "Registration Number: ");
            if (registrationNumber == null) {
                return;
            }
            if (registrationNumber.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Registration number cannot be empty. Please try again.");
            }
        } while (registrationNumber.trim().isEmpty());
        String brand;
        do {
            brand = JOptionPane.showInputDialog(this, "Brand: ");
            if (brand == null) {
                return;
            }
            if (brand.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Brand cannot be empty. Please try again.");
            }
        } while (brand.trim().isEmpty());

        String model;
        do {
            model = JOptionPane.showInputDialog(this, "Model: ");
            if (model == null) {
                return;
            }
            if (model.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Model cannot be empty. Please try again.");
            }
        } while (model.trim().isEmpty());
        String dailyRateInput;
        do {
            dailyRateInput = JOptionPane.showInputDialog(this, "Daily Rate: ");
            if (dailyRateInput == null) {
                return;
            }
            if (dailyRateInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Daily Rate cannot be empty. Please try again.");
            }
        } while (dailyRateInput.trim().isEmpty());
         
        String daysInput;
        do {
            daysInput = JOptionPane.showInputDialog(this, "Number of Days: ");
            if (daysInput == null) {
                return;
            }
            if (daysInput.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Days cannot be empty. Please try again.");
            }
        } while (daysInput.trim().isEmpty());

        String loadCapacityCharge;
        

        do {
            loadCapacityCharge = JOptionPane.showInputDialog(this, "Load Capacity Charge: ");
            if (loadCapacityCharge == null) {
                return;
            }
            if (loadCapacityCharge.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Load Capacity Charge  cannot be empty. Please try again.");
            }
        } while (loadCapacityCharge.trim().isEmpty());
        try {
            double dailyRate = Double.parseDouble(dailyRateInput.trim());
            double loadCapacity = Double.parseDouble(loadCapacityCharge.trim());
            int days = Integer.parseInt(daysInput.trim());
            if (days <= 0) {
                throw new InvalidRentalDaysException("Rental days must be greater than 0.");
            }

            Truck truck = new Truck(loadCapacity, registrationNumber, brand, model, dailyRate);
            double cost = truck.calculateRentalCost(days);

            java.io.FileWriter fw = new java.io.FileWriter("rentals.txt", true);
            fw.write("Customer: " + customerName + " | Type: Car | Reg: " + registrationNumber + " | Days: " + days + " | Total Cost: R" + cost + "\n");
            fw.close();

            JOptionPane.showMessageDialog(this, "Truck rented successfully!\nTotal Cost: R" + cost);

        } catch (InvalidRentalDaysException e) {
            JOptionPane.showMessageDialog(this, "Invalid days: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input! Numbers only for rate, fee and days.");
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "File error: " + e.getMessage());
        }
    }//GEN-LAST:event_rentAtruckActionPerformed

    private void recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordsActionPerformed
        try{
        java.io.File file = new java.io.File("rentals.txt"); 
        if(!file.exists()){
        JOptionPane.showMessageDialog(this, "No rental recors found.");
        return; 
        }
        java.util.Scanner scanner = new java.util.Scanner(file);
        StringBuilder records = new StringBuilder();
        
        while(scanner.hasNextLine()){
        records.append(scanner.nextLine()).append("\n");
        }
        scanner.close(); 
        if(records.length() == 0){
        JOptionPane.showMessageDialog(this, "No rental records found.");
        }else{
        JOptionPane.showMessageDialog(this, records.toString());
        }
        }catch(java.io.FileNotFoundException e){
        JOptionPane.showMessageDialog(this, "Filer not found "+ e.getMessage());
        }
    }//GEN-LAST:event_recordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel menu;
    private javax.swing.JButton records;
    private javax.swing.JButton rentACar;
    private javax.swing.JButton rentAMotorbike;
    private javax.swing.JButton rentAtruck;
    // End of variables declaration//GEN-END:variables
}
